<a href="https://colab.research.google.com/github/na0260/data-minig-lab/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
number = [1,2,3,4,5]
print(np.array(number)) #1d array
print(number[-1]) #last element of array
print(number[::-1]) #reverse the array
numbers = [1,2,3,4,5],["hello","world"]
print(np.array(numbers)) #2d array

[1 2 3 4 5]
5
[5, 4, 3, 2, 1]
[list([1, 2, 3, 4, 5]) list(['hello', 'world'])]


<ipython-input-9-133e9358166a>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(numbers)) #2d array


In [4]:
eye_mat = np.eye(4) #diagonals
print(eye_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
rand_num = np.random.randint(0,100,15) #random number from a range
print(rand_num)

[68 49 18 51 57 82 82 80 19 48 18 35 82 38 55]


In [10]:
mat = np.arange(1,26).reshape(5,5) #create matrix using aranged value
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [23]:
new_arr = np.arange(10)
new_arr.reshape(2,-1) # 1d to 2d array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
new_arr[(new_arr >=3) & (new_arr <= 6)]

array([3, 4, 5, 6])

In [19]:
x = np.array([1,10,5,6,3])
y = np.array([2,10,5,6,4])
np.intersect1d(x,y) #common element between two array

array([ 5,  6, 10])

In [28]:
import pandas as pd
simple_dict  = {"x":1, "y":2 ,"z":3}
series = pd.Series(simple_dict) #create series
series.name = 'numbers'
print(series)

x    1
y    2
z    3
Name: numbers, dtype: int64


In [30]:
sim_ser = pd.Series(np.random.randint(1,30,25))
dataFrame = pd.DataFrame(sim_ser.values.reshape(5,5)) #convert numpy arrays into pandas dataframe
print(dataFrame)

    0   1   2   3   4
0  26   1  12   5  26
1  22  17  29  24   3
2   4   2  27   9  26
3   9   7   7  28   4
4  15   8  24  14  19
